allegro/bigcache

- README.md
- bigcache.go
- queue/bytes_queue.go
- queue/bytes_queue_test.go
This PR fixes bug described in #1. It allows to set values bigger than currently allocated memory for cache.
> Handling values bigger than whole slice in bytes queue

- bigcache.go
- encoding.go
- encoding_test.go
Alternative implementation of wrap entry optimization proposed by @wendigo in #5 
Instead of using global sync.Pool with locks, entry byte buffer is allocated per shard.
Bench test results before and after optimization:
```
go test -bench=WriteToCacheWith -benchtime=5s
BenchmarkWriteToCacheWith1Shard-4                       5000000	     1520 ns/op
BenchmarkWriteToCacheWith500Shards-4                    	10000000	      647 ns/op
BenchmarkWriteToCacheWith1kShards-4                     10000000	      627 ns/op
BenchmarkWriteToCacheWith10kShards-4                    	10000000	      646 ns/op
BenchmarkWriteToCacheWith1kShardsAndSmallShardInitSize-4	10000000	      789 ns/op
BenchmarkWriteToCacheWith1Shard-4                       5000000	     1320 ns/op
BenchmarkWriteToCacheWith500Shards-4 …
```
> Wrap entry optimization

- README.md
- bigcache.go
- bigcache_bench_test.go
- bigcache_test.go
- caches_bench/caches_bench_test.go
- caches_bench/caches_gc_overhead_comparsion.go
- config.go
- hash.go
- hash_test.go
Hi,
I've applied two optimizations to bigcache:
- provided ability to use other hash functions like [farmhash](http://www.infoq.com/news/2014/04/google_farmhash) instead of fnv
- ensured that number of shards is power of two thus eliminating modulo operation in favor of bit mask
Results aggregated across 10 runs (before optimizations - with changes to number of shards in test cases):
```
BenchmarkWriteToCacheWith1Shard-8                           	1088 ns/op
BenchmarkWriteToCacheWith512Shards-8                        	342 ns/op
BenchmarkWriteToCacheWith1024Shards-8                       	342 ns/op
BenchmarkWriteToCacheWith8192Shards-8                       	359 ns/op
BenchmarkWriteToCacheWith1024ShardsAndSmallShardInitSize-8  	427 ns/op
BenchmarkReadFromCacheWith1024Shards-8 …
```
> Little optimizations

- README.md
- queue/bytes_queue.go
- queue/bytes_queue_test.go
When additional memory allocation occurs in bytes queue then its entries indexes should stay unchanged, because  values from bigcache map can point to them. Proposed fix fills space between tail and head pointers with an empty blob, unit tests show how bytes queue behaves in that situation.
> Entries indexes stay unchanged after additional memory allocation

- .travis.yml
Because our builds starts to fail due to problems with third party tools on go 1.7 we want to run build only on stable releases.
> Build only for go 1.6

- fnv.go
- fnv_bench_test.go
- fnv_test.go
- hash.go
Hi everyone,
Lastly I've seen 2 great tutorial how to profile and optimize Go programs. Based on that knowledge I found some small improvements in your bigcache package. I started from adding allocation reporting for all of your benchmarks. After further analysis in pprof tool it showed me that your usage of fnv64a hash function was a bit inefficient. There were 2 not necessary allocations. Here is the output of your benchmarks before the changes:
> BenchmarkWriteToCacheWith1Shard-4                            	 2000000	       963 ns/op	     617 B/op	       5 allocs/op
> BenchmarkWriteToLimitedCacheWithSmallInitSizeAnd1Shard-4     	 2000000	       828 ns/op	      65 B/op	       4 allocs/op
> BenchmarkWriteToUnlimitedCacheWithSmallInitSizeAnd1Shard-4   	 1000000	      1591 ns/op	    3470 …
> Improve fnv64a hashing algorithm by remove all allocations

- bigcache_test.go
- encoding.go
- iterator.go
No copying when converting []byte to string.
```
go test -bench BenchmarkIterateOverCache -memprofile mem.out
2016/11/03 00:29:24 Collision detected. Both "liquid" and "costarring" have the same hash 5
BenchmarkIterateOverCache/512-shards-8         	 5000000	       397 ns/op	       4 B/op	       0 allocs/op
BenchmarkIterateOverCache/1024-shards-8        	 5000000	       398 ns/op	       4 B/op	       0 allocs/op
BenchmarkIterateOverCache/8192-shards-8        	 5000000	       374 ns/op	       4 B/op	       0 allocs/op
```
Also we should use []byte keys instead of strings...
> Zero alloc byte to string conversion

- bigcache.go
- iterator.go
- shard.go
There is a known issue in Go with deferred operations being much slower than explicit operations, both directly and indirectly impacting locking.
Here are the performance comparisons (from benchstat) over 1000 iterations:
```
name                   old time/op    new time/op    delta
BigCacheSet-8             569ns ± 6%     511ns ± 5%  -10.24%  (p=0.000 n=860+949)
BigCacheGet-8             525ns ± 3%     454ns ± 5%  -13.45%  (p=0.000 n=922+930)
BigCacheSetParallel-8     178ns ± 2%     164ns ±20%   -7.61%  (p=0.000 n=961+804)
```
I did this over 1000 iterations because benchmarking nanosecond operations is hard to get consistent, so that gives a good view of the larger performance gain.
Generally, on OS X and Windows, the change gives between 10-15% performance gain.
Signed-off-by: Mike …
> Changed locking strategy

- bigcache.go
I've not found any reasons why this should stay with Lock/Unlock.
> Use RLock/RUnlock for read shard.Len

- bigcache.go
- shard.go
Looking at all usages of a shard, locks are assessed outside, but `reset` method still uses lock inside.
There is no gain in terms of performance, just consistency of the code.
> Extract Lock/Unlock from shard

- bigcache.go
- iterator.go
- iterator_test.go
- shard.go
- `Get`, `Set` methods are moved from `bigcache.go` to `shard.go`
- `initNewShard` has additional param `clock`
- all locks logic exists only inside shard
- get rid of `copyCurrentShardMap`
- `getIndex` and `oldest` methods added to shard
- introduced index variable in `getShard`
Next PR will introduce `Shard` interface, `newShard` method and additional changes.
> Improve encapsulation of shards

- bigcache_test.go
- config.go
- logger.go
- shard.go
👋 ohai !
This maintains backwards compatibility in terms of logging format, also keeps `Verbose` as main toggle.
IMO: it would look better to 🔪  `Verbose` , keep only `Logger` and have a default noop-logger. However, that means breaking api compatibility.
Fixes #36
> Adding logging interface & default logger

- README.md
- caches_bench/caches_bench_test.go
Closes #38 as it's slower than the project's implementation.
Signed-off-by: Mike Lloyd <kevin.michael.lloyd@gmail.com>
> Added concurrent maps benchmark result.

- .gitignore
- server/README.md
- server/server.go
- server/server_test.go
Features:
Basic HTTP server.
Basic middleware implementation.
I wanted to provide some thoughts on this implementation.
API Surface:
```
GET /api/v1/cache/{key}
PUT /api/v1/cache/{key}
```
The API path denotes it's an API which is versioned, so making changes/implementing new features allows it to be versioned easily. I felt `PUT` was more relevant than `POST` because `bigcache.BigCache.Set()` will overwrite an existing key of the same name. `PUT` more closely aligns with the semantic aspect of the feature as opposed to the spirit. When looking at the `/cache/` heirarchy of the path, there was a PR I saw recently which looked to implement stats about the cache. If it gets approved, you can add `/api/v1/stats` to the API surface as an extra API. Overall, this API surface seemed easily …
> Added basic HTTP server implementation.

- .travis.yml
- bigcache_test.go
- shard.go
1. Run every package on travis
2. No more race condition in `shard.GetStats`
3. No more race condition in `shard.del`
4. New `TestParallel` test to have `Set`, `Get`, `Del` operations running in parallel.
> Fix some race conditions

- README.md
- caches_bench/caches_gc_overhead_comparison.go
Looking at #59, I wanted to do a quick once over of the comparisons in
1.10 so we can make sure our numbers are still accurate. When looking
through the GC code, I discovered we are using the wrong GC stat. Using
debug.GCStats.Pause[0] uses the most recent GC pause, which can be zero
(as I found out on Windows). We should be using total pause for all
collections, which is debug.GCStats.PauseTotal. That will show the total
length of time for all GC activities during our test, which more
accurately reflects the type of comparison we are trying to show.
Also, I updated the readme to reflect our GC comparison with go1.10.
fixes #59
Signed-off-by: Mike Lloyd <mike@reboot3times.org>
> fixed gc bug and updated readme.

- .gitignore
preventing gox build artifacts from being checked in.
gox is an easy tool to cross compile for all platforms. I will use it when building release binaries, so having those artifacts be ignored is nice. see: https://github.com/mitchellh/gox
Signed-off-by: Mike Lloyd <mike@reboot3times.org>
> updated .gitignore.

- bigcache.go
- bigcache_test.go
This change makes `BigCache` an `io.Closer`. When closed, the cleaning goroutine is signaled to exit. This prevents the following:
- Stack leak due to goroutines not exiting.
- Heap leak do to the cleaning goroutine keeping a reference to the cache.
- Leak of the resources associated with maintaining the `time.Ticker`.
Fixes #82
As a test for this I wrote the following program:
```go
package main
import (
"bytes"
"log"
"runtime"
"time"
"github.com/allegro/bigcache"
)
var data = bytes.Repeat([]byte("W"), 2^24)
func main() {
go func() {
var stats runtime.MemStats
for {
runtime.ReadMemStats(&stats)
log.Printf("HeapAlloc: %d\n", stats.HeapAlloc)
log.Printf("StackSys: %d\n", stats.StackSys)
log.Printf("NumGoroutine: %d\n", runtime.NumGoroutine())
time.Sleep(3 * time.Second)
}
}()
for { …
```
> Allow for GC of cache when CleanWindow is set

- bigcache_bench_test.go
- entry_not_found_error.go
before:
```
BenchmarkReadFromCacheNonExistentKeys/1-shards-4         	 5000000	       275 ns/op	      71 B/op	       3 allocs/op
BenchmarkReadFromCacheNonExistentKeys/512-shards-4       	 5000000	       291 ns/op	      71 B/op	       3 allocs/op
BenchmarkReadFromCacheNonExistentKeys/1024-shards-4      	 5000000	       269 ns/op	      71 B/op	       3 allocs/op
BenchmarkReadFromCacheNonExistentKeys/8192-shards-4      	 5000000	       277 ns/op	      71 B/op	       3 allocs/op
```
after:
```
BenchmarkReadFromCacheNonExistentKeys/1-shards-4         	10000000	       197 ns/op	      23 B/op	       1 allocs/op
BenchmarkReadFromCacheNonExistentKeys/512-shards-4       	10000000	       187 ns/op	      23 B/op	       1 allocs/op
BenchmarkReadFromCacheNonExistentKeys/1024-shards-4      	10000000 …
```
> improved EntryNotFoundError

- iterator_test.go
- shard.go
https://github.com/allegro/bigcache/issues/107
Panic happens, when some other guy is adding new values in parallel(out of range error) because of datarace
```
WARNING: DATA RACE
Read at 0x00c006115e00 by goroutine 6:
github.com/allegro/bigcache.(*cacheShard).copyKeys()
/Users/un0/go/src/github.com/allegro/bigcache/shard.go:147 +0x74
github.com/allegro/bigcache.(*EntryInfoIterator).SetNext()
/Users/un0/go/src/github.com/allegro/bigcache/iterator.go:72 +0x1f8
github.com/un000/test/bigcache_test.TestBigCacheIter()
/Users/un0/go/src/github.com/un000/test/bigcache/cache_test.go:32 +0x2e3
testing.tRunner()
/usr/local/Cellar/go/1.11/libexec/src/testing/testing.go:827 +0x162
Previous write at 0x00c006115e00 by goroutine 11:
runtime.mapassign_fast64() …
```
> Fix data race on iteration

- bigcache.go
- bigcache_test.go
- entry_not_found_error.go
- shard.go
I reconsidered my approach to `EntryNotFoundError` error. User always knows what key he uses, so we can delete `EntryNotFoundError` structure and replace it to `ErrEntryNotFound`
```
benchmark                                                old ns/op     new ns/op     delta
BenchmarkReadFromCacheNonExistentKeys/1-shards-12        185           181           -2.16%
BenchmarkReadFromCacheNonExistentKeys/512-shards-12      182           179           -1.65%
BenchmarkReadFromCacheNonExistentKeys/1024-shards-12     184           180           -2.17%
BenchmarkReadFromCacheNonExistentKeys/8192-shards-12     182           176           -3.30%
benchmark                                                old allocs     new allocs     delta
BenchmarkReadFromCacheNonExistentKeys/1-shards-12        1 …
```
> replace EntryNotFoundError on ErrEntryNotFound

- server/server_test.go
sorry I added TestCacheIndexHandler to failed following now
on HEAD result:
```
$ cd server
$ go test -v ./...
=== RUN   TestServiceLoader
--- PASS: TestServiceLoader (0.00s)
=== RUN   TestRequestMetrics
2019/01/13 23:06:21 Entry not found
--- PASS: TestRequestMetrics (0.00s)
middleware_test.go:46: 2019/01/13 23:06:21 GET request to /api/v1/cache/empty took 180951ns.
=== RUN   TestGetWithNoKey
=== PAUSE TestGetWithNoKey
=== RUN   TestGetWithMissingKey
=== PAUSE TestGetWithMissingKey
=== RUN   TestGetKey
=== PAUSE TestGetKey
=== RUN   TestPutKey
=== PAUSE TestPutKey
=== RUN   TestPutEmptyKey
=== PAUSE TestPutEmptyKey
=== RUN   TestDeleteEmptyKey
=== PAUSE TestDeleteEmptyKey
=== RUN   TestDeleteInvalidKey
=== PAUSE TestDeleteInvalidKey
=== RUN   TestDeleteKey
=== PAUSE TestDeleteKey
=== RUN …
```
> fix server_test to clear TestCacheIndexHandler

- bigcache_test.go
- queue/bytes_queue.go
- queue/bytes_queue_test.go
- shard.go
This PR contains a testcase which demonstrates corruption (intermittently). Sometimes leading to `panic`, and sometimes leading to data corruption of values. 
I thought that fixing the datarace suggested in #117 would solve it, but it seems I was wrong about that, there's some other underlying bug. I'll push a commit on top if I find it.
> Fix data corruption (shard.go)

- server/server_test.go
#112 
I also added some tests for which increase test coverage, made it indicated to be internal server error when PUT request in server.go
> Add invalid put test that make 500 error in server

- go.mod
- go.sum
Make things a bit more portable.
Signed-off-by: Mike Lloyd <mike@reboot3times.org>
> added go mod

- config.go
Fixes an issue with the default config where no clean up is performed on cache if `CleanWindow: 0` is specified in the config.
Mentioned by @mxplusb at https://github.com/allegro/bigcache/issues/139#issuecomment-502762420
> DefaultConfig:change CleanWindow to 1 second

- README.md
This PR adds some basic information to explain the harmlessness of exponential memory usage stats that may otherwise be regarded as cause for concern.
> Add memory usage to README

- README.md
> Mention required Go version

- bigcache.go
- bigcache_bench_test.go
- bigcache_test.go
- entry_not_found_error.go
- shard.go
enhancement: added new data struct Response, which will be returned when
calling GetWithInfo(). Caller can use this Response to check the status
of the Entry, whether its Expired or not. Default '0' means its still
in use.
minor lint changes
Test: added test case for the api and made sure all tests cases are
successful
> New Get API which returns additional information about the entry

- .github/workflows/build.yml
In the `lint code` step, I made an adjustment to allow failed `goimports` command to not exit the step. I noticed that running it in travis also results in that behaviour even though it's set to fail. We could have in the future a makefile and a comment back on the commit to know what adjustments need to be done.
> Build on Github Actions

- shard.go
Optimistic locking is not working for `getWrappedEntry` because it does not return copy of data so another thread can alter the data causing panic e.g., `panic: runtime error: slice bounds out of range [:57329] with capacity 20390`. To prevent this we need to acquire lock before getting wrapped entry and release it after all operations are done.
This bug was introduced in https://github.com/allegro/bigcache/commit/0bb712de7d60f23379d438fca050e9cdeac96c91
See: 
* https://github.com/janisz/bigcache/commit/e73c96d8b9c30e2f5247ce96521edbd62b5d096b/checks
* https://storytime.dev/preview/5de55ab8ddbb4e10b45671df
> Fix issue with concurrent read/writes

- assert_test.go
- bigcache_test.go
- encoding_test.go
- go.mod
- go.sum
- iterator_test.go
- queue/bytes_queue_test.go
> Remove dependecy to testify

- README.md
As a go developer seeing mention of dynamic byte arrays was confusing since go arrays have a static length. I looked into the code and slices are indeed being used.
In go dynamic arrays are called slices which are really a pointer to a a {length, capacity, static array}. Regular arrays are a static size and cannot grow or shrink. I looked at the code and it does in fact seem to be using slices for entries. It was confusing to see 
See the go blog for further info https://blog.golang.org/go-slices-usage-and-internals
> Update README.md byte array/slice wording

- queue/bytes_queue.go
`peek` performs the same assertions as `peekCheckErr`. There is no need to keep this checks in two places.
> Replace duplicated code with function call

- shard.go
While using bigcache today I encountered this error:  
```
fatal error: concurrent map writes
goroutine 2487 [running]:
runtime.throw(0xe697aa, 0x15)
/usr/local/go/src/runtime/panic.go:774 +0x72 fp=0xc5878dd388 sp=0xc5878dd358 pc=0x4310c2
runtime.mapassign_fast64(0xd1eec0, 0xc347b05bf0, 0x44b94351220b245d, 0xc5880a8000)
/usr/local/go/src/runtime/map_fast64.go:176 +0x337 fp=0xc5878dd3c8 sp=0xc5878dd388 pc=0x413897
github.com/allegro/bigcache/v2.(*cacheShard).hit(0xc349c61560, 0x44b94351220b245d)
```
This bug was introduced by me 2 month ago instead of using `Lock` I used `Rlock`
> fix: concurrent write access

- iterator_test.go
- shard.go
Move `getOldestEntry` from production code to test where it's used.
> Move getOldestEntry to test file

- bigcache_bench_test.go
Number of shards in `read` benchmarks is always set to 1024 instead of parametrized value.
This was broken since Go 1.7 https://github.com/allegro/bigcache/commit/90098c54320d4fcf6d9f0fd8ffeed76cfb9f96c3#r36883572
> fix read benchmarks

- bigcache_test.go
- queue/bytes_queue_test.go
It looks like we reimplemented [`bytes.Repeat`](https://golang.org/pkg/bytes/#Repeat) functionality with `blob` function. Lets use as much code from stdlib as possible.
> Use bytes.Repeat instead of for loop

- .github/workflows/build.yml
Go 1.14 is around for some time
> Update Go version for CI

- bigcache_test.go
- queue/bytes_queue.go
- queue/bytes_queue_test.go
Hi there, I try to optimize bytes_queue in two ways:
1. The length is encoded in varint format(the assertion on capacity will fail so I commented them out).
2. When we insert an entry before the head of the queue, and the size of this entry exactly equals to unsued bytes, there is no need to reserve bytes. 
And below are the outputs of test on my Mac:
```
2020/03/12 14:49:28 Allocated new queue in 130ns; Capacity: 88
2020/03/12 14:49:28 Allocated new queue in 211.918µs; Capacity: 585000
2020/03/12 14:49:28 Allocated new queue in 394.027µs; Capacity: 1170000
PASS
```
```
2020/03/12 14:06:56 Allocated new queue in 156ns; Capacity: 94
2020/03/12 14:06:56 Allocated new queue in 719.26µs; Capacity: 585000
2020/03/12 14:06:56 Allocated new queue in 566.888µs; Capacity: 1170000
PASS
```
PS: It …
> Optimize bytes_queue

- bigcache_test.go
- shard.go
Hi, this is a small fix for #126,
I think the problem is that `shard.delete()` marks entries in queue as deleted ( by zero-ing all the 64 header bits for hash ), but `removeOldestEntry` is not checking for this case.
> Deleted entries should not be removed by expire eviction

- bigcache.go
- bigcache_test.go
- entry_not_found_error.go
- shard.go
> give a way to access the stale cache

- shard.go
Just noticed this typo while reading through the docs.
Please let me know if there is anything else I need to do for this PR.
> Fix typo in comment for Metadata struct

- config.go
- utils.go
https://github.com/allegro/bigcache/issues/139
> fix(init): initialShardSize ignored HardMaxCacheSize, and so the initial size can exceed the limit

- bigcache_test.go
- iterator.go
- iterator_test.go
- queue/bytes_queue.go
- queue/bytes_queue_test.go
- shard.go
1. Fix panic when update and iteration simultaneously. Related to https://github.com/allegro/bigcache/issues/222.
2. Add panic recover in cleanUp to prevent the program exited. Related to https://github.com/allegro/bigcache/issues/226, https://github.com/allegro/bigcache/issues/148, just protect the main program not exited.
3. Byte queue set full is false after allocated addition memory. Also added a test case reproduce this problem.
> fix: panic when update and iterate simultaneously

- bigcache.go
- shard.go
All(?) cases where cacheShard.getKeyMetadata() was called were wrapped in a lock, except when KeyMetadata was used, resulting in a race between when a key was deleted via cacheShard.removeOldestEntry and read via cacheShard.getKeyMetadata().
```
WARNING: DATA RACE
Write at 0x00c01697d9b0 by goroutine 133:
runtime.mapdelete_fast64()
/home/m/Documents/workspace/go/src/runtime/map_fast64.go:272 +0x0
github.com/allegro/bigcache/v2.(*cacheShard).removeOldestEntry()
/home/m/gocode/src/github.com/cognusion/bigcache/shard.go:304 +0x360
github.com/allegro/bigcache/v2.(*cacheShard).removeOldestEntry-fm()
/home/m/gocode/src/github.com/cognusion/bigcache/shard.go:293 +0x49
github.com/allegro/bigcache/v2.(*cacheShard).onEvict()
/home/m/gocode/src/github.com/cognusion/bigcache/shard.go:249 +0x1cf …
```
> Fixes race in getKeyMetadata accessor, when called from KeyMetadata

- bigcache.go
- bigcache_test.go
- config.go
- shard.go
Currently there is a mix between hard limit in memory and amount of entries used for initial capacity allocation:
initialShardSize() does a "min" on: bytes (From max shard size calculation) and amount of entries.
This leads to breaching the HardMaxCacheSize contract
> Fix in initial capacity allocation

- bigcache_test.go
- clock.go
- shard.go
For example:
```
cache := bigcache.NewBigCache(bigcache.DefaultConfig(time.Minute))
clock := &mockedClock{}
rf := reflect.ValueOf(cache).Elem().FieldByName("clock")
reflect.NewAt(rf.Type(), unsafe.Pointer(rf.UnsafeAddr())).Elem().Set(reflect.ValueOf(clock))
```
Without this change, it panics with `value of type *cache_test.mockedClock is not assignable to type bigcache.clock`
And it goes to `*cache_test.mockedClock cannot implement bigcache.Clock as it has a non-exported method and is defined in a difference package` if we only export clock interface.
Fix #241
> export clock method to allow assignable in other packages

- iterator.go
> Fix iterator styling issues

- bigcache_bench_test.go
- encoding.go
- shard.go
The append function is slow compared to the get and set method. The reason for this is that unnecessary copies of the data are done in the process. Namely, the `get` copy the data and the list `append` a second time. This leads to high allocation numbers and slow runtime overall.
In this PR the number of copies in the process is minimized without touching the `BytesQueue` logic. This reduces the allocs and halves the runtime of append without changing on the interface.
Some benchmarks result:
```
name                          old time/op    new time/op    delta
AppendToCache/1-shards-12       8.37µs ±26%    4.06µs ±23%  -51.48%  (p=0.000 n=99+98)
AppendToCache/512-shards-12     3.23µs ± 6%    1.87µs ± 3%  -42.00%  (p=0.000 n=96+92)
AppendToCache/1024-shards-12    3.49µs ± 4%    2.06µs ± …
```
> Optimze append

- queue/bytes_queue.go
- queue/bytes_queue_test.go
Hi,
On searching for the reason for the panics in the current version where versions pre 2.2 works well, I think I have found the cause. 
With PR #207 it gets possible that the byte queen is full and `q.tail == q.head`. However, in the `allocateAdditionalMemory` method, the condition for resetting head and tail is `q.tail < q.head`. Thus the tail and head are not changed, and the byte queen is obscured after it. An example that leads to panic in the old logic is shown in the test `TestPushEntryAfterAllocateAdditionMemoryInFull`.
This is a different reason for panics then #236, so I am not sure which of the reported panic ( #226 #234 #235 ) is caused by this bug.
> Fix a bug that obscures the byte queue when it is full and is extended

- README.md
We had some memory leaks in production. after further investigations, we found out that we were using big cache v1 (which interestingly HardMaxCacheSize is not working properly). I'm sure if we don't change it to version 2 it will cause some confusion.
> Update readme to version 3

- bigcache_test.go
- shard.go
issue : https://github.com/allegro/bigcache/issues/283
> fix: panic runtime error: index out of range [7] with length 0

- bigcache.go
> Remove `maxShardSize` from BigCache

- config.go
As #292 has pointed out, the documentation has misleading message for HardMaxCacheSize. 
To solve it, this PR modifies the HardMaxCacheSize comment.
> fix HardMaxCacheSize documentation

- queue/bytes_queue.go
- queue/bytes_queue_test.go
As #253 has pointed out, it is impossible to create an entry of arbitrary size in the byte queue. Basically, the problem is that at the points where the header gets larger, one number is skipped. This can lead to errors in the new allocation of a byte queue.
To solve this, the header size is included in the number that is encoded. This allows creating entries with arbitrary dimensions. For example, we have 127 bytes (1 header, 126 data), 128bytes (2 header, 126 data), and 129 bytes(2 header, 127 data).
As a benefit, we can reduce some calculations, and the code gets more straightforward. 
The only downside is that the maximum entry size reduces from `4294967296` to `4294967291` bytes. In my belief, nothing too dramatic that gets in v3 with uint64, even a more minor problem.
> The size encoded in a entry header contains the header it self.

- bigcache.go
- bigcache_test.go
Otherwise this causes more cryptic failures in later code. Best to catch this on initialization.
> Adding config validation when creating new cache.

- bigcache.go
- bigcache_test.go
- shard.go
Sometimes an error occurs to remove non-expired data when "currentTimestamp" is less than "oldestTimestamp"
> Fix bug to remove non-expired data

- bigcache_test.go
- shard.go
> Unify expiry condition in getWithInfo() and onEvict()

- bigcache.go
- bigcache_test.go
- shard.go
Hello, I saw the following issues #322 , #315 .
So I wrote the code.
> Add ResetStats

- README.md
- bigcache.go
- bigcache_bench_test.go
- bigcache_test.go
- examples_test.go
- iterator_test.go
- server/server.go
- server/server_test.go
Cleanly shutdown go routine. Big cache was made when go did not have ctx support
Fixes https://github.com/allegro/bigcache/issues/336
> Cleanly shutdown cleanup go-routine

- encoding.go
- shard.go
#350 rename resetKeyFromEntry to resetHashFromEntry
> rename resetKeyFromEntry to resetHashFromEntry

- server/cache_handlers.go
- server/server.go
- server/server_test.go
Hi, like I [mentioned](https://github.com/allegro/bigcache/issues/71) before, I did extra endpoint for clear all cache.
At the moment, i don't have enough time for change design code. I just need this endpoint for use API server.
> Added extra endpoint for clear cache

- bigcache.go
- shard.go
`errors.New` is more efficient than `fmt.Errorf` when format arg is not required
> Use errors.New instead of fmt.Errorf

- shard.go
closes  #354 
was trying to run benchmarks however when using uint32 keys i consistently ran into slice bounds out of range errors as seen below:
`BenchmarkAppendToCache/1-shards-12       panic: runtime error: slice bounds out of range [98993:98992]`
> changed to uint64 keys

- bigcache.go
- bigcache_test.go
When set CleanWindow, if LifeWindow isn't set, any data you put in will be wiped out right away. So, we need to add a check to prevent this.
> check LifeWindow when CleanWindow is set

- bigcache.go
This is mainly about the difference between `bytes store` and `bytes stored` (which I would guess is the correct thing)
> Fixing grammar in docs 
